### ISSUE TITLE
How to use the Kotlin libraries in Java projects written for Android

### ISSUE THREAD

**Issue by sajjadkhazaee** [nirukk52/SnapTabLayout#2]
I intended to use the SnapTablayout library but I did not add to the project and I wanted to know how can I add that library to a project written in Java?
(How to use the Kotlin libraries in Java projects written for Android)

**Comment by shabnamsamari** [comment]
i have exactly issues with this library. i dont know how use this in java.

**Comment by nirukk52** [comment]
Try using the latest version of the library as there have been some naming changes.

`implementation 'com.fridayof1995.tabanimation:SnapTablayout:0.0.7'`

This should solve the problem.

**Comment by sajjadkhazaee** [comment]
Could you explain how can I use this library in android project written by java?
